CCFLAGS =
CC = gcc

SOURCES_SERVER = Server.c
SOURCES_SERVER += Get_Port.c
OBJECTS_SERVER = $(SOURCES_SERVER:.c=.o)
EXECUTABLE_SERVER = Server

SOURCES_TCP_CLIENT = TCP_Client.c
SOURCES_TCP_CLIENT += Get_IP.c
SOURCES_TCP_CLIENT += Get_Port.c
OBJECTS_TCP_CLIENT = $(SOURCES_TCP_CLIENT:.c=.o)
EXECUTABLE_TCP_CLIENT = TCP_Client

SOURCES_UDP_CLIENT = UDP_Client.c
SOURCES_UDP_CLIENT += Get_IP.c
SOURCES_UDP_CLIENT += Get_Port.c
OBJECTS_UDP_CLIENT = $(SOURCES_UDP_CLIENT:.c=.o)
EXECUTABLE_UDP_CLIENT = UDP_Client

all: $(EXECUTABLE_TCP_CLIENT) $(EXECUTABLE_UDP_CLIENT) $(EXECUTABLE_SERVER)

debug: CCFLAGS += -g
#debug: CCFLAGS += -DDEBUG
debug: clean
debug: all

$(EXECUTABLE_SERVER): $(OBJECTS_SERVER)
	$(CC) $(OBJECTS_SERVER) -o $(EXECUTABLE_SERVER).elf $(CCFLAGS)

$(EXECUTABLE_TCP_CLIENT): $(OBJECTS_TCP_CLIENT)
	$(CC) $(OBJECTS_TCP_CLIENT) -o $(EXECUTABLE_TCP_CLIENT).elf $(CCFLAGS)

$(EXECUTABLE_UDP_CLIENT): $(OBJECTS_UDP_CLIENT)
	$(CC) $(OBJECTS_UDP_CLIENT) -o $(EXECUTABLE_UDP_CLIENT).elf $(CCFLAGS)

$(OBJECTS_UDP_CLIENT): $(SOURCES_UDP_CLIENT)
	$(CC) $(SOURCES_UDP_CLIENT) -c $(CCFLAGS)

$(OBJECTS_TCP_CLIENT): $(SOURCES_TCP_CLIENT)
	$(CC) $(SOURCES_TCP_CLIENT) -c $(CCFLAGS)

$(OBJECTS_SERVER): $(SOURCES_SERVER)
	$(CC) $(SOURCES_SERVER) -c $(CCFLAGS)

.PHONY: clean
clean:
	rm *.elf *.o
